### ISSUE TITLE
Ask for minimum QGIS version in metadata.txt

### ISSUE THREAD

**Issue by oesteban-vx** [florianneukirchen/qgis-project-as-utm#1]
[The plugin uses some submodules](https://github.com/florianneukirchen/qgis-project-as-utm/blob/main/projectasutm.py#L17) which are only available from some release (possibly 3.0.rc0).
```'python
from pyproj.aoi import AreaOfInterest
from pyproj.database import query_utm_crs_info
```

While the pyproj version looks rather old, looking at the place it's installed I guess it comes in the QGIS bundle. I'm not saying that QGIS 3.16 is recent enough to be supported, but the plugin should [request a minimum version in its metadata.txt](https://github.com/florianneukirchen/qgis-project-as-utm/blob/main/metadata.txt#L7).

#### Environment Information
From the QGIS python console:

```
pyproj._show_versions.show_versions()
pyproj info:
    pyproj: 2.6.1.post1
      PROJ: 7.0.1
  data dir: C:\Program Files\QGIS 3.16\apps\Python37\Lib\site-packages\pyproj\proj_dir\share\proj

System:
    python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)]
executable: C:\Program Files\QGIS 3.16\bin\qgis-ltr-bin.exe
   machine: Windows-10-10.0.18362

Python deps:
       pip: 20.2.2
setuptools: 45.2.0
    Cython: None
```

**Comment by florianneukirchen** [comment]
Fixed in 1.1 (2023-01)

 Set QGIS Minimum Version to 3.18 (the plugin requires pyproj >= 3.0.0)
